---

#######################################
### PRODUCT DEFAULTS
#######################################

# foreman_products_defaults_download_policy: on_demand
# foreman_products_defaults_mirroring_policy: mirror_complete
# foreman_products_defaults_verify_ssl_on_sync: false
# foreman_products_defaults_http_proxy_policy: global_default_http_proxy
# foreman_products_defaults_unprotected: false

### MICROSOFT

# foreman_products_defaults_download_policy_microsoft: "{{ foreman_products_defaults_download_policy }}"
# foreman_products_defaults_mirroring_policy_microsoft: mirror_content_only
# foreman_products_defaults_verify_ssl_on_sync_microsoft: "{{ foreman_products_defaults_verify_ssl_on_sync | bool }}"
# foreman_products_defaults_http_proxy_policy_microsoft: "{{ foreman_products_defaults_http_proxy_policy }}"
# foreman_products_defaults_unprotected_microsoft: "{{ foreman_products_defaults_unprotected | bool }}"
